/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSettingsRouteRouteImport } from './routes/_main/settings/route'
import { Route as MainSegmentsRouteRouteImport } from './routes/_main/segments/route'
import { Route as MainProfileRouteRouteImport } from './routes/_main/profile/route'
import { Route as MainFlagsRouteRouteImport } from './routes/_main/flags/route'
import { Route as MainAppsRouteRouteImport } from './routes/_main/apps/route'
import { Route as AuthVerifyEmailRouteRouteImport } from './routes/_auth/verify-email/route'
import { Route as AuthSignUpRouteRouteImport } from './routes/_auth/sign-up/route'
import { Route as AuthSelectOrganizationRouteRouteImport } from './routes/_auth/select-organization/route'
import { Route as AuthResetPasswordRouteRouteImport } from './routes/_auth/reset-password/route'
import { Route as AuthLoginRouteRouteImport } from './routes/_auth/login/route'
import { Route as AuthForgotPasswordRouteRouteImport } from './routes/_auth/forgot-password/route'
import { Route as AuthCreateOrganizationRouteRouteImport } from './routes/_auth/create-organization/route'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRouteRoute = MainSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSegmentsRouteRoute = MainSegmentsRouteRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileRouteRoute = MainProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFlagsRouteRoute = MainFlagsRouteRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAppsRouteRoute = MainAppsRouteRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthVerifyEmailRouteRoute = AuthVerifyEmailRouteRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRouteRoute = AuthSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSelectOrganizationRouteRoute =
  AuthSelectOrganizationRouteRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthResetPasswordRouteRoute = AuthResetPasswordRouteRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRouteRoute = AuthForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateOrganizationRouteRoute =
  AuthCreateOrganizationRouteRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/create-organization': typeof AuthCreateOrganizationRouteRoute
  '/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/reset-password': typeof AuthResetPasswordRouteRoute
  '/select-organization': typeof AuthSelectOrganizationRouteRoute
  '/sign-up': typeof AuthSignUpRouteRoute
  '/verify-email': typeof AuthVerifyEmailRouteRoute
  '/apps': typeof MainAppsRouteRoute
  '/flags': typeof MainFlagsRouteRoute
  '/profile': typeof MainProfileRouteRoute
  '/segments': typeof MainSegmentsRouteRoute
  '/settings': typeof MainSettingsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/create-organization': typeof AuthCreateOrganizationRouteRoute
  '/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/login': typeof AuthLoginRouteRoute
  '/reset-password': typeof AuthResetPasswordRouteRoute
  '/select-organization': typeof AuthSelectOrganizationRouteRoute
  '/sign-up': typeof AuthSignUpRouteRoute
  '/verify-email': typeof AuthVerifyEmailRouteRoute
  '/apps': typeof MainAppsRouteRoute
  '/flags': typeof MainFlagsRouteRoute
  '/profile': typeof MainProfileRouteRoute
  '/segments': typeof MainSegmentsRouteRoute
  '/settings': typeof MainSettingsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/create-organization': typeof AuthCreateOrganizationRouteRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRouteRoute
  '/_auth/login': typeof AuthLoginRouteRoute
  '/_auth/reset-password': typeof AuthResetPasswordRouteRoute
  '/_auth/select-organization': typeof AuthSelectOrganizationRouteRoute
  '/_auth/sign-up': typeof AuthSignUpRouteRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRouteRoute
  '/_main/apps': typeof MainAppsRouteRoute
  '/_main/flags': typeof MainFlagsRouteRoute
  '/_main/profile': typeof MainProfileRouteRoute
  '/_main/segments': typeof MainSegmentsRouteRoute
  '/_main/settings': typeof MainSettingsRouteRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-organization'
    | '/sign-up'
    | '/verify-email'
    | '/apps'
    | '/flags'
    | '/profile'
    | '/segments'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/select-organization'
    | '/sign-up'
    | '/verify-email'
    | '/apps'
    | '/flags'
    | '/profile'
    | '/segments'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/create-organization'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/select-organization'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_main/apps'
    | '/_main/flags'
    | '/_main/profile'
    | '/_main/segments'
    | '/_main/settings'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/segments': {
      id: '/_main/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof MainSegmentsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/flags': {
      id: '/_main/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof MainFlagsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/apps': {
      id: '/_main/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof MainAppsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/select-organization': {
      id: '/_auth/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof AuthSelectOrganizationRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/create-organization': {
      id: '/_auth/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof AuthCreateOrganizationRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCreateOrganizationRouteRoute: typeof AuthCreateOrganizationRouteRoute
  AuthForgotPasswordRouteRoute: typeof AuthForgotPasswordRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthResetPasswordRouteRoute: typeof AuthResetPasswordRouteRoute
  AuthSelectOrganizationRouteRoute: typeof AuthSelectOrganizationRouteRoute
  AuthSignUpRouteRoute: typeof AuthSignUpRouteRoute
  AuthVerifyEmailRouteRoute: typeof AuthVerifyEmailRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCreateOrganizationRouteRoute: AuthCreateOrganizationRouteRoute,
  AuthForgotPasswordRouteRoute: AuthForgotPasswordRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthResetPasswordRouteRoute: AuthResetPasswordRouteRoute,
  AuthSelectOrganizationRouteRoute: AuthSelectOrganizationRouteRoute,
  AuthSignUpRouteRoute: AuthSignUpRouteRoute,
  AuthVerifyEmailRouteRoute: AuthVerifyEmailRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainAppsRouteRoute: typeof MainAppsRouteRoute
  MainFlagsRouteRoute: typeof MainFlagsRouteRoute
  MainProfileRouteRoute: typeof MainProfileRouteRoute
  MainSegmentsRouteRoute: typeof MainSegmentsRouteRoute
  MainSettingsRouteRoute: typeof MainSettingsRouteRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAppsRouteRoute: MainAppsRouteRoute,
  MainFlagsRouteRoute: MainFlagsRouteRoute,
  MainProfileRouteRoute: MainProfileRouteRoute,
  MainSegmentsRouteRoute: MainSegmentsRouteRoute,
  MainSettingsRouteRoute: MainSettingsRouteRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
